### ISSUE TITLE
Metadata extension / Custom fields Backend

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#10]
### Goal

Allow instances to configure custom fields and make them available in the deposit form and on the landing page.

### Tasks

- Backend:
    - [x] Schema: Fully integrated with services schema data validation and JSONSchema - reenable feature.
    - [x] Indexing: ES dumper extension to correctly index edtf dates
- REST API/Service:
    - [x] Search by custom fields (search filters).
- Configuration:
    - [x] How to configure custom fields.
    - [x] Titles for defined fields is required to display them properly
- Deposit form:
    - [x] Automatic creation of widget fields per section.
    - [x] Support ordering of fields
    - [x] Implement JS fields per type (strinng, bool, number, edtf, arrays of each one)
- Landing page:
    - [x] Display custom metadata on landing page per section (support ordering of sections)
- Docs:
    - [x] Configuring custom fields.

#### Bottom of landing page with metadata.

![Screenshot 2020-10-06 at 15 31 37](https://user-images.githubusercontent.com/1698163/95208157-06ee7f80-07e9-11eb-8643-096e8eb62bd0.png)
