### ISSUE TITLE
Linked records

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#11]
### Goal

Allow interlinking of records (bibliographic with license, grant, organisation, funder, grant) including integration in the deposit form.

### Tasks

Needed for: Licenses, grants, subjects, languages

- New module
    - [x] JSONSchema(s), Mappings, API, Service, Resource, Config, Permission Policy, REST API
    - [x] Support python backed, file backed and record backed vocabularies.
- Backend:
    - [x] ~~Implement completion suggester in Records-Resources.~~
    - [x] System field for Linked Record (+ dereferencing mechanism)
    - [x] Indexing and reindexing (some fields should be dumped, others not)
    - [x] Marshmallow schema and fields that can clean data to DB.
- Deposit form:
    - [x] Auto-complete fields and tag field. Selection of vocabulary
    - [x] Frontend fields:
        - [x] License selector widget
        - [x] Subjects field
        - [x] Language selector field.
        - [x] Grants, funders (should allow both auto-completetion and insertion of new objects)
- APIs:
    - [ ] REST APIs to import data: upload to bucket, run an import job.
- Landing page:
    - [x] Display vocabularies
    - [x] Display license with icon and link and help text
- Vocabularies:
    - [ ] Record backed:
        - [x] Licenses 
           - [ ] Data import from SPDX
        - [ ] Grants
           - [ ] Data import from OpenAIRE. 
        - [ ] Organisations
           - [ ] Data import from ROR
        - [ ] Funders
           - [ ] Data import from Open Funder Registry
        - [ ] Subjects
           - [ ] Data import from MeSH.
        - [x] Languages
    - File backed:
        - [ ] Resource Types
        - [ ] Contributor roles

#### Example UI from Zenodo

![Screen Recording 2020-10-06 at 15 34 18 mov](https://user-images.githubusercontent.com/1698163/95208606-9f84ff80-07e9-11eb-9246-501bac0afce8.gif)

#### Mockup for deposit form

![Screenshot 2020-10-06 at 15 38 24](https://user-images.githubusercontent.com/1698163/95208887-fa1e5b80-07e9-11eb-88b9-4d4a962eb85f.png)

**Comment by lnielsen** [comment]
The main part of the work was implemented in the December Invenio sprint.

- Sprint goals: https://github.com/inveniosoftware/invenio/issues/4056
- 


Left-overs that wasn't implemented has been logged in #48 (postponed) and #49 (to be scheduled)

**Comment by lnielsen** [comment]
### Stats

- Estimated efforts: 16 weeks
- Committed efforts: 10 weeks (5 developers during 10 days). Does not include work done prior to the sprint in order to write the RFCs. 
- Estimated left-over tasks 4-8 weeks
