### ISSUE TITLE
Deposit form UX

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#12]
### Goal

Ensure the deposit form styling and user experience looks very nice.

### Tasks

- Deposit form:
    - [ ] Help icons with text
    - [ ] Form error feedback
    - [ ] Error messages
- Deposit form widgets
   - [ ] Publication date field  with EDTF support
   - [x] Description field with WYSIWYG editor.
   - [x] Authors/contributors front-end field
   - [x] Date ranges
- Design:
   - [x] Clean-up design
   - [ ] Styling

**Comment by lnielsen** [comment]
Some examples of the update deposit form. A lot of work was done, but still not finished

![Screenshot 2021-02-01 at 11 43 15](https://user-images.githubusercontent.com/1698163/106448159-ad3e4f00-6482-11eb-8951-d436832986f3.png)
 
![Screenshot 2021-02-01 at 11 43 33](https://user-images.githubusercontent.com/1698163/106448629-54bb8180-6483-11eb-8f7f-3bce118d7740.png)

![Screenshot 2021-02-01 at 11 43 38](https://user-images.githubusercontent.com/1698163/106448631-55ecae80-6483-11eb-913a-562596c6dc70.png)
