### ISSUE TITLE
Usage statistics

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#13]
### Goals

Enable usage statistics

### Tasks

- Backend:
    - [ ] System field for usage statistics
    - [ ] Dumper: include in ES record, not in DB record
    - [ ] Reindexing of record and versions
    - [ ] Configuration of background task for aggregation
- Search page
    - [ ] Display usage statistics:
        - [ ] views, downloads
- Landing page:
    - [ ] Display usage metrics (like zenodo)
        - [ ] via statistics system field
        - [ ] via statistics counting (with community)
- REST API
    - [ ] Serialization of statistics in JSON (Marshmallow schema)
- Export:
    - [ ] Export to DataCite usage statistics
- Docs:
    - [ ] Explain usage statistics (take from Zenodo FAQ)

- Excludes:
   - Reporting and community usage statistics pages.

### Mockups

![Screenshot 2020-10-06 at 15 56 33](https://user-images.githubusercontent.com/1698163/95211156-829dfb80-07ec-11eb-94d4-ac20dece6446.png)

**Comment by lnielsen** [comment]
Don't display file downloads for metadata only records: https://github.com/inveniosoftware/invenio-app-rdm/issues/197
