### ISSUE TITLE
Preservation

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#15]
### Goal

Ensure RDM is using best practice for preservation.

### Tasks

- Backend
    - [x] File integrity checks (configure)
    - [x] File integrity report (configure and migrate zenodo)
 - SIP package on publish, edit, new version
   - Implement new OCFL module

- Record soft-deletion:
  - Landing page:
      - [x] Tombstone page with removal reasons
  - Management:
      - [x] Record deletion (allowing specifying removal reason). start with soft-deletion via requests
  - Schemas/validation:
      - Enable validation of record deleteion schema.

**Comment by lnielsen** [comment]
Potential for data futures to take on the OCFL task with help.

**Comment by lnielsen** [comment]
Closing as basic features are done. New discussions happening about integrating e.g. Archivematica
