### ISSUE TITLE
Serializations (export formats)

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#16]
### Goal

Ensure RDM is working properly with reference managers, search engines (scholar, dataset search) and harvesters.

###  Tasks
(port from Zenodo)

- Landing page:
    - Export pages
    - [ ] Embed JSON-LD in page
    - [ ] Embed highwire press tags (Scholar)
- Serializers:
    - JSON-LD (required)
    - [ ] BibTex (required) (boderline)
    - Dublin Core  (required)
    - DataCite XML (required)
    - DCAT-AP (required)
    - GeoJSON (nice-to-have)
    - MARCXML (nice-to-have)
    - MODS (nice-to-have) using MARCXML->MODS XSLT    
- Run test on landing page according to
    - https://www.nature.com/articles/s41597-019-0031-8
    - Google Dataset Search
    - OpenAIRE Guidelines

**Comment by lnielsen** [comment]
Done
