### ISSUE TITLE
Citations generation

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#17]
### Goal

Show citations on the landing page

Approach:
- Minimal thing (goal is to reach the basic plumbing as fast as possible):
  - A CSL serializer that takes not paramters (hard-coding style and loacle)
  - A citation string serializer that uses the CSL JSON serializer to generate a citation string (again hard-coded style and locale)
  - Build a simple React app that displays the citation (for one style)
- Next step:
  - Extend with locale/style query parameters
  - Extend the react app to use styles
- End steps:
  - import CSL styles as a fixture.

### REST API - Citation generation on the records API

You can query a single record for a citation string:

```console
$ curl -k -H "Accept: text/x-bibliography" "https://127.0.0.1:5000/api/records/12345-abcde?locale=en-US&style=3d-printing-in-medicine"
HTTP/1.1 200 Ok
...
Content-Type: text/plain

1. De Bruin, J. Novel Coronavirus (COVID-19) Cases in The Netherlands. Zenodo; 2020.
```

Or you search for records:

```console
$ curl -k -H "Accept: text/x-bibliography" "https://127.0.0.1:5000/api/records?q=my+query&locale=en-US&style=3d-printing-in-medicine"

1. De Bruin, J. Novel Coronavirus (COVID-19) Cases in The Netherlands. Zenodo; 2020.
2. ....
```

In both cases there two new parameters:

1. ``locale`` - the locale use to generate the citation
2. ``style`` the name of the citation style file to use.

#### Tasks:

- [x] Release a new version of [citeproc-py-styles](https://github.com/inveniosoftware/citeproc-py-styles) with updated style files.
- [x] Build a CSL JSON serializer in ``invenio_rdm_records/resources/serializers/csl/``.
    - [x]  (content type: ``'application/vnd.citationstyles.csl+json``)
- [x] Build a citation string serializer.  CSL JSON serializer in ``invenio_rdm_records/resources/serializers/csl/``.
    - [x] content-type: ``text/x-bibliography``
- [x] Map the two serializers in the [resource config](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/resources/config.py#L22-L25)
- [x] Add a ``@request_args`` decorator to [Invenio-Records-Resources](https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/resources/records/resource.py#L88):

```python
request_view_args = request_parser from_conf('request_args'), location='args')
```
This allows you to override the URL querystring parameter parsing in RDM-Records. Then you need to add ``locale`` and ``style`` to both the ``request_search_args`` and ``request_args``.

- [ ] Create a new ``ResponseHandler()`` which able to pass the locale/style to the serializer.

Old examples from Zenodo:
- [Definition](https://github.com/zenodo/zenodo/blob/master/zenodo/modules/records/serializers/__init__.py#L132-L135)
- [Schema doing the mapping from a Zenodo record to a CSL JSON](https://github.com/zenodo/zenodo/blob/c3fb663ba840f3b51a828e535948d8ff78b8067a/zenodo/modules/records/serializers/schemas/csl.py#L57)
- [Citeproc serializer](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/serializers/citeproc.py)
- 
- Attention: The [CSL type](https://github.com/zenodo/zenodo/blob/c3fb663ba840f3b51a828e535948d8ff78b8067a/zenodo/modules/records/serializers/schemas/csl.py#L134-L138) should be determined by the resource type vocabulary which define a CSL type. Ask Guillaume/Pablo how to get a cached version of all resource types with the CSL mapping.

### REST API - CSL Styles

The list of available styles can be imported as a generic vocabulary, by defining it in Invenio-RDM-Records and load the data.

```
% curl  https://127.0.0.1:5000/api/vocabularies/citationstyles

{...}
```

### Landing page

![Screenshot 2020-10-06 at 16 12 43](https://user-images.githubusercontent.com/1698163/95213136-c4c83c80-07ee-11eb-88f6-e99c679ebf64.png)

Tasks:

- [x] Config
- [x] Landing page React app
- [x] Export page

#### App-RDM ``config.py``

Invenio-App-RDM should allow to the list of citation style that we can between (see "Style" in mockup):

```python
RDM_CITATION_STYLES = [
     ('chicago', _('Chicago')),
     ('ieee', _('IEEE')),
     # ...
]
```

Also, you should be able to define the default citation style:

```python
RDM_DEFAULT_CITATION_STYLE = 'chicago'
```

#### React app

Above config should be fed to a React-App, that will use it to render the citation string as in the mockup. When the App is loading it should display a placeholder.

ATTENTION: We will not do the "Search style" search box this month.

#### Export page

- Add a ``CSL JSON`` export option using the CSL JSON serializer:

![Screenshot 2021-05-31 at 15 18 09](https://user-images.githubusercontent.com/1698163/120199415-7fe09280-c223-11eb-87db-4f43a770e4d0.png)

### Documentation

- [ ] Add a new section under [Customize InvenioRDM](https://inveniordm.docs.cern.ch/customize/) named: ``Landing page``. The page should document how to change the configuration variables to adjust the citation styles displayed. Specifically it should explain which citation styles are possible.

-  [ ] Add the two configuration variables to ``https://inveniordm.docs.cern.ch/reference/configuration/`` - reference style documentation. Use the same style as this page: https://inveniordm.docs.cern.ch/install/configuration/#app_allowed_hosts
