### ISSUE TITLE
Metadata schema

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#2]
**Goal**

Finalise the metadata fields of the data model so that other code can depend on it.

**Tasks**

- Metadata fields (no access, no files, etc):
    - [x] JSONSchema 
    - [x] Marshmallow schema update
    - [x] ES mapping update.
    - [x] Basic marshmallow data validation.
    - [x] Implement all basic validation.
- Service:
    - [x] ESDumper extension for EDTF publication_date.
- REST API:
    - Sort
        - [x] Define the default sort fields for RDM.
    - Facets
        - [x] Define default facets for RDM.
        - [x] Support for nested facets (e.g. resource type) - mapping and indexing.
- Customization:
    - Configuration
        - [x] Allow overriding configuration some few options.
        - [x] Allow service to configure ES dumper extensions.
