### ISSUE TITLE
Communities: Basics

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#22]
### Goals

Enable creation of communities and finalize the core data models

### Tasks

- Design:
  -  [x] RFC REST API, 
- Service/data access layer:
  - [x] Logo upload
  - [x] Permissions - new permission policy
  - [x] Data model and systemfields
- REST API:
  - [x] Communities REST API
- UI:
  - [x] Communities search page (frontpage)
  - [x] Single Community Landing Page
  - [x] New community form
  - [x] Settings page
- UX:
  - [x] Polished UX for the current community
