### ISSUE TITLE
Basic landing and search page

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#4]
### Goal

Update landing page and search results to make use of the data model updates, and ensure display of most the metadata fields. Display placeholders for things not yet available.

### Tasks

- Config:
    - [x] Option to disable placeholders in interface
- REST API:
    - [x] Include rendered/localized text JSON output (e.g. EDTF date) for use in search results.
    - [x] Include titles for facets and sort options in JSON output.
- Search page: 
    - [x] Facets (including titles)
    - [ ] Display configured sort options
    - [x] Add placeholders: version switch (all versions or latest versions only).
    - [x] Finish styling the search result item template (JSX)
- Landing page:
    - [x] Display all metadata fields
    - [x] Display placeholders:
        - [x] management: edit, new version, delete
        - [x] versions
        - [x] usage metrics
        - [x] citation
        - [x] send message
        - [x] community
        - [x] export formats

#### Search results

![Search](https://user-images.githubusercontent.com/1698163/95187956-14e1d780-07cc-11eb-9d6a-00c2abaac47a.png)

#### Landing page (anonymous user, no community)

![Landing page copy](https://user-images.githubusercontent.com/1698163/95187733-c7fe0100-07cb-11eb-9700-bf51c576717b.png)
)

#### Landing page (owner, no community)

![Landing page (Uploader view)](https://user-images.githubusercontent.com/1698163/95189212-dc42fd80-07cd-11eb-8333-d4de2ac9b4bc.png)

#### Landing page (custom metadata, community display

![Landing page (Treatment)](https://user-images.githubusercontent.com/1698163/95189254-ea911980-07cd-11eb-9389-88d837d9bd2c.png)
)
