### ISSUE TITLE
Advanced files

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#40]
### Goals

Allow file uploads via a third-party storage system and support extra metadata as well as the ordering of files.

### Tasks

- Backend
    -  [x] Easier multi backend support
    - [x] System fields for files 
        - [ ] Extra metadata: description
    - [x] File service:
       - [x] Implement a file service, which basically manages record.files.
- REST API
    - [ ] Finalise design of new REST API
    - [ ] New file upload API (needed for extra metadata).
- Deposit form:
    - [x] Adapt react file uploader to work with new API.
    - [ ] Add support in react file uploader for extra metadata as well as ordering.
    - [ ] Add quota display
- Config:
   - [ ] Flag to enable/disable metadat only records globally on an instance.
   - [ ] Restrict searches to not query on files (use LUQUM query parser)?
- Upload via a third-party storage system.

#### Deposit form

![Screenshot 2020-10-07 at 23 10 52](https://user-images.githubusercontent.com/1698163/95388295-59679300-08f2-11eb-8aca-91924cc4c698.png)

**Comment by lnielsen** [comment]
- files: implement garbage collection in files-rest of files instances that have no references.

**Comment by lnielsen** [comment]
- Indexing and search for files - some thoughts in https://github.com/inveniosoftware/invenio-rdm-records/issues/287

**Comment by lnielsen** [comment]
Done
