### ISSUE TITLE
Release v1.0

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#42]
### Goal 

Provide a stable release of InvenioRDM

### Tasks

-  [x] Release all relevant modules
-  [ ] Thoroughly test the upgrade from v1.0 to v2.0
-  [ ] Write automated upgrade recipes OR document the upgrade process
- [ ] Describe all breaking changes.

Notes:

- CLI:
  - Execution of upgrade scripts
  - Alembic upgrades
  - Reindexing
  - Package upgrades

- Cookiecutter:
  - Upgrade of the core files: docker, pipfile (can we separate core packages from non-core).
  - Templates

- Docs (2 days):
  - Maintenance policy
  - Release policy (now and future): LTS with monthly releases.
  - Write an upgrade contract with the user?

- Stable:
  - REST API serialization (JSON output)
  - Internal metadata.
  - Vocabulary files.
  - Templates: Jinja templates, Result templates
