### ISSUE TITLE
Release v4.0

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#44]
### Goal 

Provide a stable release of InvenioRDM

### Tasks

-  [ ] Release all relevant modules
-  [ ] Thoroughly test the upgrade from v3.0 to v4.0
-  [ ] Write automated upgrade recipes OR document the upgrade process
- [ ] Describe all breaking changes.
