### ISSUE TITLE
Release 5.0

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#45]
### Goal 

Provide a stable release of InvenioRDM

### Tasks

-  [ ] Release all relevant modules
-  [ ] Thoroughly test the upgrade from v4.0 to v5.0
-  [ ] Write automated upgrade recipes OR document the upgrade process
- [ ] Describe all breaking changes.
