### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#5]
### Goal

Finalise the versioning implementation backend/frontend (minus the external PID registration)

### Tasks

- Deposit form:
    - [x] Discard button to discard the a new version
- Search page + list uploads
    - [x] Flip switch on search result page
    - [x] Sort by version number
    - [x] Filter by versions
    - [x] Result template updates (display link to other versions)
- Landing page:
    - [x] Right hand column display of versions.
    - [x] Version alerts on landing page and link to new version
    - [x] Button + view for creation of new verison 
    - [x] Check UI flow for new version creation.
- REST API support
    - [x] ``/api/records?all_versions`` (include/exclude previous versions)
    - [x] ``/api/records?sort=versions`` (sort in version order)
    - [x] ``/api/records?parent=`` (filter to versions of a record)
    - [x] New version creation endpoint ``POST /records/:id/versions``.
- Backend
    - [x] New system field: relations (responsible for seralizing relations into the record).
    - [x] ESDumper: correct dumping of relations in index
    - [x] PID relations: Redirect of latest record
    - [x] Custom check to see if publishing is allowed (e.g. are the files the same)
- No community integration (but shouldn't be necessary)

- Excluded:
    - Checking if files are the same
    - Registering external PIDs
#### Search filter to toggle between latest/all versions
![Screenshot 2020-10-06 at 13 34 20](https://user-images.githubusercontent.com/1698163/95196683-b2430880-07d8-11eb-9564-645ff849b5c4.png)

#### Landing page header when not latest

![Screenshot 2020-10-06 at 13 35 37](https://user-images.githubusercontent.com/1698163/95196764-d272c780-07d8-11eb-9c5a-7a3ff21b09b9.png)

#### Versions box on landing page

![Screenshot 2020-10-06 at 13 36 16](https://user-images.githubusercontent.com/1698163/95196819-e9b1b500-07d8-11eb-8267-50cb53661ccd.png)

#### Landing page button for new version creation

![Screenshot 2020-10-06 at 13 39 04](https://user-images.githubusercontent.com/1698163/95197073-4dd47900-07d9-11eb-9f88-244826f247ec.png)

#### Deposit form  discard button

![Screenshot 2020-10-06 at 13 41 46](https://user-images.githubusercontent.com/1698163/95197332-bcb1d200-07d9-11eb-86b8-e4ac0aac0c68.png)
