### ISSUE TITLE
Communities: REST API for record integration and inclusion request

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#52]
### Goal

Integrate communities with the records.

### Tasks

- Design:
  -  [x] RFC Requests data model, REST API, ...
- Backend:
  - [x] Requests permissions/routing
  - [x] Extend parent record with community information?
  - [x] Record reindexing
- Deposit form:
   - [ ] Integrate the community into the deposit form.
   - [ ] Allow community curators to edit metadata
- Communities:
   - [ ] Requests Inbox tab (search over requests)
   - [ ] Requests detail page: accept/reject
- Landing page: 
   - [ ] Style according to community
   - [ ] Request inclusion of record in community (create an inclusion request)
- Profile:
   - [ ] Personal Requests Inbox
