### ISSUE TITLE
Fixture data import and sync performance

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#56]
### Goal

Goal significantly improve data import speed for both records, vocabularies and fixtures

### Tasks

- Fixture loading:
  - [ ] Build commands for dumping/loading database tables and indexes, so that we can dump and restore something like affiliation data much faster (basically for speed, avoid passing through the Python layer).
  - [ ] Tools for having an overview over how much data is loaded and the speed
  - [ ] Build tools for performing sync between new versions of the data (e.g. a new ROR dump).
