### ISSUE TITLE
Access control

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#6]
### Goal

Restrict access to deposit form, search and display records only to users allowed to view them.

### Tasks

- Design:
  - [x] Finalise mockup of sharing widget in deposit form
  - [x] Finalise mockup of protection widget in deposit form
- Metadata schema
  - Access field: 
    - [x] public/private metadata and public/private files
    - [x] ownership
    - [x] embargo date
    - [x] access condition
    - [ ] provenance and contact?
- Backend
  - [x] Permission policy:
    - [x] Definition of access levels. 
    - [x] Implement missing need generators.
  - [x] Integrate with records/drafts-resources: search and individual records
  - [x] Integrate with files-rest
  - [x] Integrate with records-ui
  - [ ] Embargo date updater
  - [x] Use permission policy for accessing files
- Protect the  REST API
  - [x] /records/
  - [x] /records/:id/draft
  - [x] /user/records
  - [ ] include access status (open, closed, embargoed, restricted) in JSON response in REST API.
- Landing page
  - [x] Landing page should require login if private
  - [ ] Display access status: open, closed, emargoed, restricted? how does this work with
- Deposit form:
  - [x] Deposit form page should require login.
  - [x] Implement protection widget
    - [x] Public/Private 
    - [x] Private files 
    - [x] Access condition
    - [x] Embargo period
- List user uploads:
  - [x] Page should require login (and specific permission ``can_list``).
    - [x] Define facets (according to mockups)
    - [x] Define sort (according to mockups)
- Docs:
  - [ ] Collect examples of how to custmoize the permission policy (IP based access control)

- Excludes:
  - Sharing (i.e. private means owners only)
  - Get a link
  - Access requests UI

#### Protection widget

![Screenshot 2020-10-06 at 14 10 52](https://user-images.githubusercontent.com/1698163/95199929-e10fad80-07dd-11eb-8eb0-1df3a26e0cc9.png)

#### Sharing widget

![Screenshot 2020-10-06 at 14 11 34](https://user-images.githubusercontent.com/1698163/95199923-df45ea00-07dd-11eb-8e9f-e1fbe2fa767a.png)

### List uploads

![Screenshot 2020-11-09 at 14 39 13](https://user-images.githubusercontent.com/1698163/98548103-684ab800-2299-11eb-9511-4d6609e4eb4e.png)

**Comment by lnielsen** [comment]
Missing: 
- Embargo updater
- Display access status: open, closed, emargoed, restricted? how does this work with
- Docs: Collect examples of how to custmoize the permission policy (IP based access control)
- Data model:  provenance and contact?
