### ISSUE TITLE
Files

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#7]
### Goals

Allow large file uploads via deposit form, access control on files, display and search.

See also #40

### Tasks

- Design:
    - [x] Bucket flow: Snapshotting, locking, one bucket, not many, editing of files after publication.
    - [x] Metadata only records.
    - [x] Select the file previewed by default.
    - [x] Extra metadata for file: order/default preview
- Backend
    - [x] System fields for files 
        - [x] Dumping in index and db record
        - [x] Utilities: snaptshotting, locking, creation + a way to hook into it (e.g. quotas, s3) 
        - [x] Integrate system field into service.
- REST API
    - [x] Reuse Invenio-Files-REST API.
- Landing page
    - [x] Display list of files (according to permissions)
        - [x] JS app to load file in preview of when preview button is clicked.
- Deposit form:
    - [x] Bug fixes for react file uploader
    - [x] Integration of uploader with form
    - [x] Integration of file uploader with REST API
    - [x] Metadata only check box
- [x] Previewers
    - [x] Enable default available previewers.

### Excludes

- Extra metadata (like description)

#### Landing page file listing

![Screenshot 2020-10-06 at 14 47 14](https://user-images.githubusercontent.com/1698163/95203288-d4da1f00-07e2-11eb-9616-ee9982e5d0a8.png)

#### Deposit form

![Screenshot 2020-10-07 at 23 10 52](https://user-images.githubusercontent.com/1698163/95388295-59679300-08f2-11eb-8aca-91924cc4c698.png)

**Comment by lnielsen** [comment]
## User stories

- **Deposit form (before publishing)**
    - As a user, I want upload very large files (100GB+) via my browser, so that I don't have to use other complicated tools.
    - As a user, I want to drag and drop files, so that I don't have to use the file browser.
    - As a user, I want to see my file quota, so that I know how much space I have available.
    - As a user, I want to delete an already uploaded file, so that can correct mistakes.
    - As a user, I want to stop an ongoing upload, so that I can correct mistakes.
    - As a user, I want my uploads to start immediately, so that I don't have to manually start an upload.
    - As a user, I want to see the progress of my file uploads, so I know how long time is left.
    - As a user, I want to be able to download an uploaded file, so that I can check it is the correct one.
    - As a user, I want to see the file checksum, size, name, so that I can check it is the correct one.
    - As a user, I want to not upload files, so that I can create a metadat only record.
    - As a admin, I want to disable the possibility to not uploads files, so that I can require all records to have a file.
    - As an admin, I want to limit max number of files allowed to be uploaded, so that users don't upload 1000+ files.
    - As a user, I want to know that I cannot change files after uploaded, so that it doesn't come as a surprise.
- **Deposit form (after publishing)**
    - As a user, I want to see the files I uploaded in the record.
    - As an admin, I do not want users to change files after publishing, so that records can be properly cited.
    - As an user, I want to select the default file being previewed on the landing page, so that I can show the best file on my landing page. 
- **Landing page**
    - As a visitor, I want to see a list of files in the record, so that I can search.
    - As a visitor, I want to see a preview of the best/most important file, so that I can better understand the record.
