### ISSUE TITLE
Basic UX

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#8]
### Goals

Ensure that the user experience looks and feels like top of the class UX.

### Tasks

- UX: polish and styling
    - [x] Two layer footer
    - [x] Shadows in layout
    - [x] General styling improvements
- Search:
    - [x] UX on search interface (minor layout changes)
    - [x] Record item template (styling)
    - [x] Titles in facets including REST API support
    - [x] Links in the bottom of facets: search guide
- Settings page
    - [x] UX and styling (font sizes, alignment, ...)
