### ISSUE TITLE
DOI minting support (+ other PID schemes)

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#9]
### Goals

Handle registration and management of external persistent identifiers like DataCite DOIs.

### Tasks

- Design:
    - [x] Record metadata design: providers, clients
    - [x] Management of DOIs (e.g. deregister local DOI because external DOI exists and vice versa)
- Backend:
    - [x] System fields for persistent identifiers
        - [x] Examples: DataCite DOI, DOE DOI, External DOI, OAI-PMH ID, Handle
        - [x] Multi client support (i.e. different credentials for registering with DataCite)
        - [ ] Versioning: Concept DOI and Redirection (using what have already been developed with versioning)
    - [x] Serialization format:
        - [x] DataCite JSON (XML not needed)
        - [x] Serialization for concept record in DataCite JSON (port from Zenodo)
    - Celery tasks:
        - [x] Use new DataCite REST API (PR from Tom)
        - [x] Tasks for checking for failed registrations and reregistering (migrate zenodo)
    - Publish workflow:
        - [x] Allow running tasks before/after.
- Service:
    - [x] Service schema data validation
    - [x] Service level components 
- Deposit form:
    - [x] Mockup: Design
    - [x] Pre-reserve feature for datacite DOIs (+automatic deposit creation)
    - [x] Implement fields 
- Landing page:
    - [x] DOI badge for both version and parent record.
    - [x] DOIs in the versions list
- [x]  Search results/list uploads (to be done maybe in the future)
    - [x] Display DOI on result item.

#### Record metadata

```json
{ 
   "pids": {
        "doi": {"value": "10.5281/zenodo.1234", "provider": "datacite", "client": "zenodo"},
        "doi": {"value": "10.7612/abcd", "provider": "datacite", "client": "cern-yr"},
        "doi": {"value": "10.1234/abcd", "provider": "external"},
        "concept-doi": {},
        "handle": {"value": "9.12314", "provider": "cern-handle", "client": "zenodo"},
        "oai": {"value": "oai:zenodo.org:12345", "provider": "zenodo"},
    }
}
```

#### Deposit form

![DOI](https://user-images.githubusercontent.com/1698163/95206676-43b97700-07e7-11eb-9bda-d79974aca755.png)
